apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    controller: Replicaset-nginx
  ports:
  - protocol: TCP
    port: 80        # Defines the Service's port within the cluster
    targetPort: 80  # Defines the Pod's port
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    controller: Replicaset-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx        # must be the same value as the label in the template 
  template:
    metadata:
      labels:
        app: nginx      # this label is assigned to each pod in the set
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        - containerPort: 80
        